    <!-- Preloader -->
    <div id="preloader">
        <div id="status">&nbsp;</div>
    </div>
    <!-- Main content -->
    <?php $base_url = base_url(); ?>
    <section class="page-error">
        <div class="text-center">
            <h1><img src="data_assets/img/OS-logo.png" class="oslogo"/>ICT <span>Department</span></h1>
        </div>
        <div class="headline-lock text-center" id="time">
            <span></span>
            <!-- Time auto generated by js -->
        </div>
        <?php 
            echo form_open('verify_user');
        if ($is_lock) { ?>
        <div class="lockscreen-name"><?php echo $name; ?></div>
        <div class="lockscreen-image">
            <img src="<?php echo $img_url; ?>" alt="user image" />
        </div>
        <input type="hidden" name="username" value="<?php echo $un; ?>"/>
        <?php } else { ?>
        <div class="lockscreen-item">
            <!-- lockscreen credentials (contains the form) -->
            <div class="lockscreen-credentials">
                <div class="well">
                    <div class="col-sm-12 input-group">
                        <input type="text" name="username" class="form-control" placeholder="Username/Email">
                    </div>
                </div>
            </div>
            <!-- /.lockscreen credentials -->
        </div>
        <?php } ?>
        <div class="lockscreen-item">
            <!-- lockscreen credentials (contains the form) -->
            <div class="lockscreen-credentials">
                <div class="well">
                    <div class="col-sm-12 input-group">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                        <div class="input-group-btn">
                        <button class="btn btn-flat"><i class="fa fa-arrow-right text-muted"></i>
                        </button>
                    </div>
                    </div>
                </div>
            </div>
            <!-- /.lockscreen credentials -->
        </div>
        <!-- /.lockscreen-item -->
        <?php echo form_close(); ?>
        <div class="lockscreen-link">
        <?php if ($registration_result == 'success') { ?>
        <h4>You've been successfully added to database!</h4>
        <?php } else if ($registration_result == 'fail') { ?><h4>Something went wrong! Please register again... :(</h4><?php } ?>
        <?php if ($is_lock) { ?>
            <a class="lock-link" href="logout">or sign in as a different user...</a>
        <?php } else { ?>
            No account yet? <a class="lock-link" href="register">register now!</a>
        <?php } ?>
        </div>
        <?php echo validation_errors('<div class="lockscreen-link">*', '</div>'); ?>
    </section>